# Generated by Django 2.1.1 on 2018-09-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180923_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='concentration',
        ),
        migrations.AddField(
            model_name='node',
            name='concentration',
            field=models.ManyToManyField(related_name='concentration', to='main.Concentration'),
        ),
    ]
