# Generated by Django 2.1.1 on 2018-09-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180923_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='key',
        ),
    ]
