# Generated by Django 2.1.1 on 2018-09-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_course_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
