# Generated by Django 2.1.1 on 2018-09-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='key',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
