# Generated by Django 2.1.1 on 2018-11-24 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20180930_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.Concentration')),
                ('courses_taken', models.ManyToManyField(related_name='_userprofile_courses_taken_+', to='main.Course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.Major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
