# Generated by Django 2.1.1 on 2018-11-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_major_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='concentration',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.Concentration'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='courses_taken',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_courses_taken_+', to='main.Course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.Major'),
        ),
    ]
