# Generated by Django 2.1.1 on 2018-11-24 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181124_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='concentration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.Concentration'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.Major'),
        ),
    ]
