# Generated by Django 2.1.1 on 2018-11-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181124_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_time_logged_in',
            field=models.BooleanField(default=True),
        ),
    ]
