# Generated by Django 2.1.1 on 2018-11-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userprofile_first_time_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.TextField(choices=[('S', 'Spring'), ('F', 'Fall'), ('B', 'Both')], default='F', max_length=2),
        ),
    ]
