# Generated by Django 2.1.1 on 2018-11-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_course_prereqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='node',
            name='course',
        ),
        migrations.RemoveField(
            model_name='node',
            name='parent',
        ),
    ]
