# Generated by Django 2.1.1 on 2018-09-11 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180910_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='concurrent_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Course'),
        ),
    ]
